spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec-202210a
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-site
server:
  servlet:
    context-path: /ec-site
